### ISSUE TITLE
TypeError: Cannot read property 'location' of null

### ISSUE THREAD

**Issue by sefn** [sebgroup/ng-magic-iframe#8]
## How to reproduce

1) I import ng-magic-iframe in my angular project. This is my template:

`<seb-ng-magic-iframe [source]="'https://cio-stage-acc.sebshift-px.sebank.se/pqq_portal/sebflow/login?mocked=true'"></seb-ng-magic-iframe>`

I run my angular application with ng serve and try to open localhost:4200.

## Actual result

The page loads but it's empty with console errors. I can see that the ng-magic-iframe and the iframe within and everything looks good in the DOM tree.

I get this console log error:
`TypeError: Cannot read property 'location' of null`

when the page loads.

## Root cause

It seems like contentDocument is undefined, in this line of code:

https://github.com/sebgroup/ng-magic-iframe/blob/a27cada9e7aa0273e0813d08f930348816bb5bbc/projects/ng-magic-iframe/src/lib/components/ng-magic-iframe.component.ts#L244

**Comment by hjalmers** [comment]
This is probably a CORS issue as you're most likely not allowed to access the contentDocument of the document. We can't do much about it other than improve error handling...

**Comment by sefn** [comment]
@hjalmers Ah okay, makes sense, thank you.
